#!/usr/bin/env bash

apt update

## required
apt install \
    vim \
    build-essential \
    ca-certificates \
    curl \
    wget \
    cloc



## python
apt install \
    python-is-python3 \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    llvm \
    libncurses5-dev \
    lzma-dev


# for wsl2
apt install \
    keychain
